[package]
name = "xmz"
version = "0.1.0"
edition = "2024"

[dependencies]
memchr = "2"
memmap2 = "0.9.7"
ratatui = "0.26"
crossterm = "0.27"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3
